# Generated by Django 6.0.3 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
