# Generated by Django 6.0.3 on 2026-03-15

from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("users", "Category")
    for name in ["Web Development", "UI/UX Design", "Mobile Apps"]:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_project_add_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customuser",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hourly_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/cover/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="users", to="users.category"),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("level", models.PositiveSmallIntegerField(default=50)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="skills", to="users.customuser")),
            ],
            options={
                "ordering": ("-level", "name"),
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("company", models.CharField(max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="experiences", to="users.customuser")),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="portfolio/")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="portfolio_items", to="users.customuser")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
